//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1022 版自动生成。
// 
#pragma warning disable 1591

namespace WindowsFormsApplication2.gwxxWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="baseServiceSoap", Namespace="http://sjbg.xxjwd.org/")]
    public partial class baseService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback initPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback setTqyjPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback setNewPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProductByPNameOperationCompleted;
        
        private SjbgSoapHeader sjbgSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback getApkVerCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public baseService() {
            this.Url = global::WindowsFormsApplication2.Properties.Settings.Default.WindowsFormsApplication2_gwxxWebService_gwxxWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SjbgSoapHeader SjbgSoapHeaderValue {
            get {
                return this.sjbgSoapHeaderValueField;
            }
            set {
                this.sjbgSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event initPasswordCompletedEventHandler initPasswordCompleted;
        
        /// <remarks/>
        public event setTqyjPasswordCompletedEventHandler setTqyjPasswordCompleted;
        
        /// <remarks/>
        public event setNewPasswordCompletedEventHandler setNewPasswordCompleted;
        
        /// <remarks/>
        public event getUserByIdCompletedEventHandler getUserByIdCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event getProductByPNameCompletedEventHandler getProductByPNameCompleted;
        
        /// <remarks/>
        public event getApkVerCodeCompletedEventHandler getApkVerCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sjbg.xxjwd.org/initPassword", RequestNamespace="http://sjbg.xxjwd.org/", ResponseNamespace="http://sjbg.xxjwd.org/")]
        public bool initPassword() {
            object[] results = this.Invoke("initPassword", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void initPasswordAsync() {
            this.initPasswordAsync(null);
        }
        
        /// <remarks/>
        public void initPasswordAsync(object userState) {
            if ((this.initPasswordOperationCompleted == null)) {
                this.initPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitPasswordOperationCompleted);
            }
            this.InvokeAsync("initPassword", new object[0], this.initPasswordOperationCompleted, userState);
        }
        
        private void OninitPasswordOperationCompleted(object arg) {
            if ((this.initPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.initPasswordCompleted(this, new initPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sjbg.xxjwd.org/setTqyjPassword", RequestNamespace="http://sjbg.xxjwd.org/", ResponseNamespace="http://sjbg.xxjwd.org/")]
        public bool setTqyjPassword(int uid, string newPass) {
            object[] results = this.Invoke("setTqyjPassword", new object[] {
                        uid,
                        newPass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setTqyjPasswordAsync(int uid, string newPass) {
            this.setTqyjPasswordAsync(uid, newPass, null);
        }
        
        /// <remarks/>
        public void setTqyjPasswordAsync(int uid, string newPass, object userState) {
            if ((this.setTqyjPasswordOperationCompleted == null)) {
                this.setTqyjPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetTqyjPasswordOperationCompleted);
            }
            this.InvokeAsync("setTqyjPassword", new object[] {
                        uid,
                        newPass}, this.setTqyjPasswordOperationCompleted, userState);
        }
        
        private void OnsetTqyjPasswordOperationCompleted(object arg) {
            if ((this.setTqyjPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setTqyjPasswordCompleted(this, new setTqyjPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sjbg.xxjwd.org/setNewPassword", RequestNamespace="http://sjbg.xxjwd.org/", ResponseNamespace="http://sjbg.xxjwd.org/")]
        public bool setNewPassword(string user_no, string newPass) {
            object[] results = this.Invoke("setNewPassword", new object[] {
                        user_no,
                        newPass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void setNewPasswordAsync(string user_no, string newPass) {
            this.setNewPasswordAsync(user_no, newPass, null);
        }
        
        /// <remarks/>
        public void setNewPasswordAsync(string user_no, string newPass, object userState) {
            if ((this.setNewPasswordOperationCompleted == null)) {
                this.setNewPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetNewPasswordOperationCompleted);
            }
            this.InvokeAsync("setNewPassword", new object[] {
                        user_no,
                        newPass}, this.setNewPasswordOperationCompleted, userState);
        }
        
        private void OnsetNewPasswordOperationCompleted(object arg) {
            if ((this.setNewPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setNewPasswordCompleted(this, new setNewPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sjbg.xxjwd.org/getUserById", RequestNamespace="http://sjbg.xxjwd.org/", ResponseNamespace="http://sjbg.xxjwd.org/")]
        public User getUserById(string user_no) {
            object[] results = this.Invoke("getUserById", new object[] {
                        user_no});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void getUserByIdAsync(string user_no) {
            this.getUserByIdAsync(user_no, null);
        }
        
        /// <remarks/>
        public void getUserByIdAsync(string user_no, object userState) {
            if ((this.getUserByIdOperationCompleted == null)) {
                this.getUserByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserByIdOperationCompleted);
            }
            this.InvokeAsync("getUserById", new object[] {
                        user_no}, this.getUserByIdOperationCompleted, userState);
        }
        
        private void OngetUserByIdOperationCompleted(object arg) {
            if ((this.getUserByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserByIdCompleted(this, new getUserByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sjbg.xxjwd.org/login", RequestNamespace="http://sjbg.xxjwd.org/", ResponseNamespace="http://sjbg.xxjwd.org/")]
        public bool login(string user_no, string user_pass) {
            object[] results = this.Invoke("login", new object[] {
                        user_no,
                        user_pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string user_no, string user_pass) {
            this.loginAsync(user_no, user_pass, null);
        }
        
        /// <remarks/>
        public void loginAsync(string user_no, string user_pass, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        user_no,
                        user_pass}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sjbg.xxjwd.org/getProductByPName", RequestNamespace="http://sjbg.xxjwd.org/", ResponseNamespace="http://sjbg.xxjwd.org/")]
        public Product getProductByPName(string pname) {
            object[] results = this.Invoke("getProductByPName", new object[] {
                        pname});
            return ((Product)(results[0]));
        }
        
        /// <remarks/>
        public void getProductByPNameAsync(string pname) {
            this.getProductByPNameAsync(pname, null);
        }
        
        /// <remarks/>
        public void getProductByPNameAsync(string pname, object userState) {
            if ((this.getProductByPNameOperationCompleted == null)) {
                this.getProductByPNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProductByPNameOperationCompleted);
            }
            this.InvokeAsync("getProductByPName", new object[] {
                        pname}, this.getProductByPNameOperationCompleted, userState);
        }
        
        private void OngetProductByPNameOperationCompleted(object arg) {
            if ((this.getProductByPNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProductByPNameCompleted(this, new getProductByPNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SjbgSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://sjbg.xxjwd.org/getApkVerCode", RequestNamespace="http://sjbg.xxjwd.org/", ResponseNamespace="http://sjbg.xxjwd.org/")]
        public ApkInfo getApkVerCode() {
            object[] results = this.Invoke("getApkVerCode", new object[0]);
            return ((ApkInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getApkVerCodeAsync() {
            this.getApkVerCodeAsync(null);
        }
        
        /// <remarks/>
        public void getApkVerCodeAsync(object userState) {
            if ((this.getApkVerCodeOperationCompleted == null)) {
                this.getApkVerCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetApkVerCodeOperationCompleted);
            }
            this.InvokeAsync("getApkVerCode", new object[0], this.getApkVerCodeOperationCompleted, userState);
        }
        
        private void OngetApkVerCodeOperationCompleted(object arg) {
            if ((this.getApkVerCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getApkVerCodeCompleted(this, new getApkVerCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://sjbg.xxjwd.org/")]
    public partial class SjbgSoapHeader : SoapHeader {
        
        private string aField;
        
        private string pField;
        
        /// <remarks/>
        public string A {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        public string P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://sjbg.xxjwd.org/")]
    public partial class ApkInfo {
        
        private int verCodeField;
        
        private string verNameField;
        
        private string uRLField;
        
        private string fileNameField;
        
        /// <remarks/>
        public int VerCode {
            get {
                return this.verCodeField;
            }
            set {
                this.verCodeField = value;
            }
        }
        
        /// <remarks/>
        public string VerName {
            get {
                return this.verNameField;
            }
            set {
                this.verNameField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://sjbg.xxjwd.org/")]
    public partial class Product {
        
        private int pidField;
        
        private string pNameField;
        
        private string servicePageField;
        
        /// <remarks/>
        public int Pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <remarks/>
        public string PName {
            get {
                return this.pNameField;
            }
            set {
                this.pNameField = value;
            }
        }
        
        /// <remarks/>
        public string ServicePage {
            get {
                return this.servicePageField;
            }
            set {
                this.servicePageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://sjbg.xxjwd.org/")]
    public partial class User {
        
        private int uidField;
        
        private string userNameField;
        
        private string userNoField;
        
        private int userDeptField;
        
        /// <remarks/>
        public int Uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserNo {
            get {
                return this.userNoField;
            }
            set {
                this.userNoField = value;
            }
        }
        
        /// <remarks/>
        public int UserDept {
            get {
                return this.userDeptField;
            }
            set {
                this.userDeptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void initPasswordCompletedEventHandler(object sender, initPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class initPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal initPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setTqyjPasswordCompletedEventHandler(object sender, setTqyjPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setTqyjPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setTqyjPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setNewPasswordCompletedEventHandler(object sender, setNewPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setNewPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setNewPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getUserByIdCompletedEventHandler(object sender, getUserByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getProductByPNameCompletedEventHandler(object sender, getProductByPNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProductByPNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProductByPNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getApkVerCodeCompletedEventHandler(object sender, getApkVerCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getApkVerCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getApkVerCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApkInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApkInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591